// ─────────────────────────────────────────────────────────────
// SEWE, Blog & Prêmio content
// HOW TO ADD A POST (no admin needed):
//   1. Add an entry to the SEWE_POSTS array below.
//   2. Duplicate an existing post HTML file (e.g. vencedor-premio-2025-diamaju.html),
//      rename it to "<slug>.html", and change data-slug to your new slug.
//   3. Commit + push. Done, it shows up on /blog and (if category:'premio') on /premio.
//
// category: 'premio'  → also listed on the Prêmio page (winners)
//           'blog'    → general article
//
// blocks types: { type:'p', text } paragraph · { type:'h', text } subtitle
//   { type:'quote', text, who } · { type:'stat', value, label }
//   { type:'list', items:[...] } · { type:'lead', text } big intro line
//   { type:'metrics', items:[{value,label}] } highlighted result grid
// logo: optional path to the winner's logo (shown on the cover instead of a metric)
// references: optional [{ label, url }] — fontes de autoridade citadas no texto
// ─────────────────────────────────────────────────────────────

// Perfis de autor (caixa do autor + JSON-LD author/sameAs). Chave = post.author.
window.SEWE_AUTHORS = {
  'Alex de Souza': {
    role: 'Diretor Comercial · Sócio-fundador da SEWE Group',
    photo: '/assets/autor-alex-souza.jpg',
    bio: 'Sócio-fundador da SEWE Group, acompanha de perto distribuidores de todo o Brasil na jornada de transformar dados em decisão comercial, do estoque à diretoria.',
    linkedin: 'https://www.linkedin.com/in/alexsouzasewegroup/',
  },
};

window.SEWE_POSTS = [
  {
    slug: 'informacao-e-poder-distribuicao',
    category: 'blog',
    title: 'Informação é poder: inteligência de dados na distribuição',
    date: '2026-09-05',
    readTime: '8 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'Da CIA à KGB, quem domina a informação primeiro domina o jogo. Na distribuição, a sua vantagem competitiva são os dados da operação. Veja como usá-los.',
    cover: { tag: 'GESTÃO · INTELIGÊNCIA DE DADOS · ESTRATÉGIA', metric: 'BI', metricLabel: 'a sua agência de inteligência' },
    cta: { primary: 'Agendar Diagnóstico de Inteligência de Dados', secondary: 'Falar com um Especialista' },
    blocks: [
      { type: 'lead', text: 'A história provou: quem domina a informação antes de todo mundo domina o jogo. George H. W. Bush e Vladimir Putin não chegaram ao topo por sorte. Antes do poder, ambos passaram por escolas de inteligência, a CIA e a KGB, onde aprenderam a transformar dados dispersos em vantagem estratégica. No mercado de hoje, a sua distribuidora joga a mesma partida, e a sua agência de inteligência são os dados da própria operação.' },
      { type: 'h', text: 'O tabuleiro da CIA e a disciplina da KGB' },
      { type: 'p', text: 'Bush pai foi diretor da CIA antes de chegar à presidência dos Estados Unidos: teve o mapa do xadrez global em mãos antes dos outros players. Putin construiu sua ascensão depois de anos na KGB, onde mapear vulnerabilidades e oportunidades virou método. O padrão comum não é o cargo, é o domínio da informação estruturada. Quem lê os sinais primeiro decide primeiro, e decide melhor.' },
      { type: 'p', text: 'Comece pela trajetória de Bush. Aos 20 anos, era um dos aviadores navais mais jovens dos Estados Unidos; foi abatido sobre o Pacífico em 1944 e resgatado no mar por um submarino, o USS Finback. Antes da política, montou uma empresa de petróleo no Texas. Depois vieram o Congresso, a embaixada na ONU e a chefia da missão diplomática na China, até assumir a direção da CIA em 1976, num dos piores momentos da agência, abalada por escândalos e desconfiança pública. Sua missão ali foi reorganizar a inteligência americana. Não por acaso, a sede da CIA leva hoje o nome dele.' },
      { type: 'p', text: 'Putin seguiu o caminho oposto, mas com a mesma matéria-prima. Formado em Direito em Leningrado, entrou para a KGB em 1975 e serviu por cerca de 16 anos, boa parte como oficial de inteligência em Dresden, na Alemanha Oriental. Quando o Muro de Berlim caiu, ele estava lá, queimando documentos enquanto o regime ruía ao redor. Saiu do serviço como tenente-coronel, entrou para a administração pública de São Petersburgo e, em menos de uma década, chegou ao comando do país. A escola era a mesma: coletar, cruzar e interpretar informação melhor, e antes, do que os outros.' },
      { type: 'p', text: 'Repare no que os dois têm em comum, e no que não têm. Não é carisma, não é sorte, não é sequer o cargo. É método. Ambos foram formados em ambientes onde a informação certa, na hora certa, valia mais que qualquer recurso. Aprenderam a transformar ruído, boatos, relatórios soltos e dados dispersos em leitura de cenário. E quem lê o cenário primeiro, age primeiro.' },
      { type: 'p', text: 'Agora troque a CIA e a KGB pela sua distribuidora, e o tabuleiro global pelo seu mercado regional. A pergunta que fica é incômoda: enquanto você fecha o mês olhando pelo retrovisor, quem no seu setor já está lendo os sinais em tempo real? É essa vantagem, silenciosa e decisiva, que separa quem cresce de quem só reage. E ela começa com uma decisão simples sobre os seus próprios dados, como você vai ver a seguir.' },
      { type: 'image', src: '/assets/blog/informacao-e-poder-distribuicao/command-room.jpg', alt: 'Sala de comando com mapa-múndi de operações e dashboards, equipe analisando dados em tempo real', caption: 'A informação vira poder quando a operação lê os sinais em tempo real, antes dos concorrentes.' },
      { type: 'h', text: 'Dados brutos são ruído. Informação é munição.' },
      { type: 'p', text: 'Ter dados não é ter inteligência. O ERP da sua distribuidora acumula milhões de registros de estoque, vendas, positivação e financeiro, mas dado bruto, sem estrutura e sem leitura, é apenas ruído. Inteligência é o que sobra quando você organiza esse volume, cruza as variáveis certas e enxerga o sinal antes do concorrente. É a diferença entre reagir ao mês fechado e antecipar o próximo movimento.' },
      { type: 'h', text: 'A sua distribuidora é o novo campo de batalha' },
      { type: 'p', text: 'A inteligência mais valiosa da sua operação não está em um relatório de mercado pago: está nos seus próprios dados de estoque e vendas. Quem opera sem BI joga no escuro, decide por instinto e deixa o lucro preso no processo. Quem estrutura esses dados enxerga onde ganha e onde perde dinheiro, todos os dias. Três perguntas que a sua operação precisa responder em tempo real:' },
      { type: 'list', items: [
        'Onde o seu capital de giro está parado, entre curva ABC e aging de estoque.',
        'Quais clientes estão esfriando antes de virarem churn, e por quê.',
        'Qual mix e qual margem sustentam de verdade o resultado, e quais só dão volume.',
      ]},
      { type: 'callout', text: 'Informação estruturada é munição. Na disputa por mercado, vence quem interpreta os sinais primeiro, não quem acumula mais relatórios.' },
      { type: 'h', text: 'A SEWE é a sua agência de inteligência privada' },
      { type: 'p', text: 'É esse o papel da SEWE Group: transformar o caos do seu ERP em vantagem competitiva. Estruturamos os seus dados, entregamos inteligência aplicada à distribuição, sobre a plataforma Qlik, e recuperamos o lucro que ficava retido no processo. Não é mais um painel para você configurar; é decisão pronta para agir, do estoque à diretoria.' },
      { type: 'quote', text: 'Você não precisa de mais um dashboard. Precisa de inteligência: dado estruturado que vira decisão antes do concorrente. É isso que devolve o lucro que estava preso na operação.', who: 'Alex de Souza · Diretor Comercial, SEWE Group' },
    ],
    references: [
      { source: 'Encyclopaedia Britannica', label: 'George H. W. Bush', url: 'https://www.britannica.com/biography/George-H-W-Bush', note: 'Diretor da CIA (1976-77) antes da vice-presidência e da presidência dos EUA.' },
      { source: 'Encyclopaedia Britannica', label: 'Vladimir Putin', url: 'https://www.britannica.com/biography/Vladimir-Putin', note: 'Ex-oficial da KGB antes da ascensão política na Rússia.' },
    ],
  },
  {
    slug: 'qlik-cloud-ia-governanca-distribuicao',
    category: 'blog',
    title: 'Qlik Cloud: IA e governança de dados na distribuição',
    date: '2026-08-07',
    readTime: '6 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'Os avanços do Qlik Cloud em IA, governança e produtividade mudam o jogo dos dados. Veja o que isso significa para a gestão da sua distribuidora.',
    cover: { tag: 'BUSINESS INTELLIGENCE · QLIK · IA APLICADA', metric: 'Qlik', metricLabel: 'parceira oficial · BI para distribuição' },
    cta: { primary: 'Agendar Diagnóstico de Dados e BI', secondary: 'Falar com um Especialista' },
    blocks: [
      { type: 'lead', text: 'Os avanços recentes do Qlik Cloud deixam clara uma direção: inteligência artificial, governança e produtividade de dados estão convergindo para uma só estratégia. Para a distribuição, que decide todo dia sobre ruptura, mix, crédito e capital de giro, isso significa transformar dado confiável em decisão mais rápida, sem abrir mão de controle. Como parceira oficial Qlik, a SEWE traduz esses avanços na linguagem do seu negócio.' },
      { type: 'h', text: 'IA mais perto de quem decide' },
      { type: 'p', text: 'A maior mudança não é ter mais gráficos, e sim conversar com os dados. Com analytics aumentada e busca em linguagem natural sobre bases governadas, o usuário deixa de esperar pelo relatório e passa a perguntar. No chão da distribuição, é o gerente perguntando "quais clientes da Curva A caíram de positivação neste mês?" e recebendo a resposta na hora, a partir do dado que já estava na plataforma, e não em uma planilha paralela.' },
      { type: 'image', src: '/assets/blog/qlik-cloud-ia-governanca-distribuicao/qlik-dashboard.jpg', alt: 'Profissional analisando um painel do Qlik Cloud com receita, margem bruta e vendas por região', caption: 'Do dado ao painel: a gestão da distribuidora sobre o Qlik, em uma só tela.' },
      { type: 'h', text: 'Governança: IA só vale com dado confiável' },
      { type: 'p', text: 'Quanto mais a IA entra na decisão, mais importa de onde vem o dado. É por isso que governança deixou de ser burocracia e virou pré-requisito. Definições consistentes, segurança e rastreabilidade são o que permitem confiar em uma resposta automática, ainda mais numa operação com várias filiais, dezenas de representantes e um ERP no centro.' },
      { type: 'list', items: [
        'Definições únicas dos indicadores (margem, ruptura, positivação) para toda a empresa, do campo à diretoria.',
        'Segurança em nível de linha: cada filial e cada representante enxerga apenas o que é seu.',
        'Rastreabilidade do dado, da origem no ERP até o painel de quem decide.',
      ]},
      { type: 'h', text: 'Produtividade: menos atrito entre o dado e a decisão' },
      { type: 'p', text: 'O terceiro vetor é operacional: integrar dados, automatizar rotinas e concentrar tudo em um só ambiente. Pipelines governados mantêm os dados do ERP sempre atualizados, e automações disparam o alerta certo na hora certa (ruptura iminente na Curva A, cliente em risco de churn, desvio de meta) antes que o problema apareça no fechamento do mês.' },
      { type: 'callout', text: 'A vantagem competitiva não está em ter mais dashboards. Está em encurtar a distância entre um dado confiável e a decisão de comprar, vender ou conceder crédito.' },
      { type: 'h', text: 'O papel da SEWE sobre o Qlik' },
      { type: 'p', text: 'A plataforma da Qlik é de classe mundial, mas é horizontal: serve a qualquer setor. O trabalho da SEWE é verticalizar, entregando sobre o Qlik um BI com DNA de distribuição, já modelado para Curva ABC, ruptura, mix, positivação, DRE e capital de giro. Você não recebe mais uma ferramenta para configurar; recebe decisão pronta para agir.' },
      { type: 'quote', text: 'A tecnologia da Qlik é de classe mundial. O nosso trabalho é fazer com que ela fale a língua da distribuição, transformando associação de dados em decisão de compra, venda e crédito.', who: 'Alex de Souza · Diretor Comercial, SEWE Group' },
    ],
    references: [
      { source: 'Qlik', label: 'Qlik Cloud: analytics, IA e integração de dados', url: 'https://www.qlik.com/us/products/qlik-cloud', note: 'Plataforma de dados e IA que sustenta o BI da SEWE.' },
      { source: 'Qlik', label: 'Qlik Talend Data Integration e governança de dados', url: 'https://www.qlik.com/us/data-integration', note: 'Integração e governança que garantem dado confiável para alimentar a IA.' },
      { source: 'NowVertical / Grupo IN', label: 'Qlik Cloud avança em IA, governança e produtividade de dados', url: 'https://nowvertical-pt.in1.com.br/blog/qlik-cloud-avanca-em-ia-governanca-e-produtividade-de-dados', note: 'Panorama das atualizações recentes do Qlik Cloud que inspirou esta análise.' },
    ],
  },
  {
    slug: 'churn-silencioso-distribuicao',
    category: 'blog',
    title: 'O Inimigo Oculto das Vendas: Como Identificar e Reverter o Churn Silencioso',
    date: '2026-08-07',
    readTime: '5 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'O churn silencioso drena sua receita sem avisar. Aprenda a identificar sinais de abandono na carteira B2B e como a análise de dados pode salvar vendas.',
    cover: { tag: 'COMERCIAL · RETENÇÃO & CARTEIRA', metric: '−36,27%', metricLabel: 'de queda no faturamento histórico da carteira' },
    cta: { primary: 'Agendar Diagnóstico de Carteira e Churn', secondary: 'Falar com um Especialista' },
    blocks: [
      { type: 'lead', text: 'Sabe aquele cliente fiel que, de repente, começa a comprar um pouco menos? Ele não abre chamados de reclamação, não envia e-mails pedindo cancelamento e nem avisa que está cotando com a concorrência. Ele simplesmente vai, aos poucos, desaparecendo. Esse é o churn silencioso (ou soft churn), o inimigo invisível que corrói as margens da sua empresa mês após mês, mascarado por números globais de faturamento que, num primeiro momento, parecem saudáveis.' },
      { type: 'h', text: 'O que realmente é o churn silencioso?' },
      { type: 'p', text: 'No mercado B2B ou no varejo recorrente, o encerramento formal de um contrato nem sempre acontece. O churn silencioso se manifesta pelo declínio gradual do engajamento. O cliente deixa de interagir com o vendedor, passa a ignorar e-mails de marketing e, principalmente, espaça o tempo entre os pedidos.' },
      { type: 'callout', text: 'Atenção: se você espera o cliente ficar 6 meses sem comprar para considerá-lo perdido, você já chegou tarde demais para salvá-lo. O resgate precisa ser proativo.' },
      { type: 'h', text: 'Os sinais claros de que um cliente está esfriando' },
      { type: 'p', text: 'Como não há um pedido de cancelamento formal, o time comercial precisa ter processos analíticos afiados para detectar a evasão. Fique atento a estes sintomas:' },
      { type: 'list', items: [
        'Queda drástica no ticket médio: o cliente costumava gastar R$ 10.000 mensais e passou para R$ 3.000. Ele está suprindo a demanda principal em outro fornecedor.',
        'Mudança no intervalo de compras (RFM): se a frequência histórica de um cliente era de 15 em 15 dias e já se passaram 45 dias sem novos orçamentos, o alerta vermelho deve acender.',
        'Ausência de novas cotações: o cliente não apenas parou de comprar, como parou de cotar. Isso indica uma ruptura no relacionamento ou na percepção de competitividade.',
        'Engajamento nulo: reuniões adiadas, mensagens não respondidas pelo WhatsApp e nenhuma interação com os pontos de contato da empresa.',
      ]},
      { type: 'image', src: '/assets/blog/churn-silencioso-distribuicao/churn-silencioso.jpg', alt: 'Infográfico do churn silencioso: relacionamento esfriando e queda invisível de engajamento antes do cancelamento', caption: 'O churn silencioso aparece nos dados de engajamento muito antes do cancelamento formal.' },
      { type: 'h', text: 'O custo da desatenção: o que os dados nos dizem' },
      { type: 'p', text: 'Quando olhamos para operações comerciais robustas sem acompanhamento em tempo real, os números assustam. O retrato abaixo vem de uma análise de carteira conduzida pela SEWE Group:' },
      { type: 'metrics', items: [
        { value: '1.590', label: 'clientes positivados na base ativa aparente' },
        { value: '908', label: 'clientes em churn (compraram há 6 meses, inativos há 3)' },
        { value: '889', label: 'clientes em churn sem nenhum orçamento ativo' },
        { value: '103', label: 'clientes em churn efetivamente resgatados' },
        { value: 'R$ 5.629,17', label: 'de ticket médio em risco por cliente perdido' },
      ]},
      { type: 'p', text: 'Os 908 clientes em churn representam risco iminente de evasão em mais de 50% da carteira transacional, e o resgate de apenas 103 deles mostra o quanto as campanhas de reativação ainda precisam de reforço. Estes números provam que focar apenas na aquisição de novos clientes é como encher um balde furado.' },
      { type: 'quote', text: 'O churn silencioso não é a perda do cliente hoje, mas a falência da sua previsibilidade de receita amanhã. É a métrica mais letal justamente porque não faz barulho.' },
      { type: 'h', text: 'Como a inteligência de dados muda o jogo' },
      { type: 'p', text: 'Para reverter o churn silencioso, o time de vendas não pode depender de planilhas defasadas. É necessário um sistema de Business Intelligence que mapeie o comportamento de compra quase em tempo real, como os painéis de gestão comercial da SEWE. Uma gestão eficiente de carteira deve incluir:' },
      { type: 'list', items: [
        'Visão de clientes frequentes sem compra no mês atual: atacar o problema no dia 20, antes que o cliente complete um mês zerado.',
        'Ranking de maiores quedas: entender não só quem parou de comprar, mas quem diminuiu o volume de faturamento em relação ao ano anterior.',
        'Histórico de atividade (dias sem compra): classificar a base em faixas (16 a 30 dias, 91 a 180 dias) para direcionar campanhas específicas. Clientes na faixa de 30 dias precisam de relacionamento; acima de 90 dias, precisam de ofertas agressivas de recuperação.',
      ]},
      { type: 'h', text: 'Próximos passos para blindar sua carteira' },
      { type: 'p', text: 'Não espere o cliente ir para a concorrência. Implemente rotinas semanais de análise de carteira e capacite os vendedores para realizarem contatos investigativos: notamos que seu volume diminuiu, como podemos ajudar?' },
    ],
    references: [
      { source: 'Bain & Company', label: 'Prescription for cutting costs', url: 'https://www.bain.com/insights/prescription-for-cutting-costs/', note: 'Aumentar a taxa de retenção de clientes em 5% eleva os lucros entre 25% e 95%.' },
      { source: 'Harvard Business Review', label: 'The Value of Keeping the Right Customers', url: 'https://hbr.org/2014/10/the-value-of-keeping-the-right-customers', note: 'Por que reter a base certa custa menos e rende mais do que adquirir novos clientes.' },
    ],
  },
  {
    slug: 'split-payment-distribuicao',
    category: 'blog',
    title: 'Split Payment na distribuição: o fim do float tributário',
    date: '2026-07-17',
    readTime: '7 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'O Split Payment (IBS/CBS) acaba com o float tributário e pressiona o capital de giro da distribuição. Veja como a inteligência de dados protege o caixa.',
    cover: { tag: 'FINANÇAS AVANÇADAS · REFORMA TRIBUTÁRIA · SUPPLY CHAIN', metric: 'IBS·CBS', metricLabel: 'recolhimento automático na fonte' },
    cta: { primary: 'Agendar Diagnóstico de Impacto de Caixa e Reforma Tributária', secondary: 'Falar com um Especialista' },
    blocks: [
      { type: 'lead', text: 'O ecossistema de distribuição no Brasil sempre usou uma ferramenta informal, porém vital, para financiar suas operações: o float tributário. No modelo tradicional, a empresa fatura a mercadoria, recebe o valor bruto do cliente e usa esse montante como um "empréstimo involuntário" e sem juros do governo por 30, 40 ou até 60 dias, recolhendo os impostos apenas no mês seguinte. Com a chegada definitiva do Split Payment sob a égide do IBS e da CBS, esse pulmão financeiro deixa de existir.' },
      { type: 'p', text: 'O funcionamento do novo mecanismo é implacável: no exato instante em que o comprador liquida a transação eletrônica (seja via Pix, boleto ou cartão), o arranjo de pagamento segrega os valores. O montante devido ao Fisco é direcionado automaticamente para a conta do Comitê Gestor (CGIBS) e da Receita Federal. O distribuidor, portanto, só toca no valor líquido da mercadoria. O imposto nunca mais transita pela esfera patrimonial ou pelo caixa da sua empresa.' },
      { type: 'image', src: '/assets/blog/split-payment-distribuicao/caixa-sob-pressao.jpg', alt: 'Infográfico do Split Payment: o valor da venda dividido entre imposto e caixa da empresa', caption: 'No Split Payment, o imposto é separado no ato da venda, e o caixa sente na mesma hora.' },
      { type: 'h', text: 'O descasamento de prazos: a armadilha do Split Payment no capital de giro' },
      { type: 'p', text: 'Para o setor de distribuição, o Split Payment gera uma assimetria temporal perigosa. Se a sua empresa vende em prazos longos ao cliente final (60 ou 90 dias), mas o regime de competência exige o reconhecimento do débito tributário na emissão da nota, o seu caixa será severamente pressionado. Você precisará financiar o tributo retido na origem muito antes de ver a cor do dinheiro da venda, exigindo uma injeção massiva de capital de giro próprio ou a contratação de linhas de crédito bancárias caras.' },
      { type: 'list', items: [
        'O fim da liquidez artificial: empresas que usavam o dinheiro do imposto acumulado no mês para pagar fornecedores de curto prazo enfrentarão uma crise imediata de liquidez se não recalcularem sua Demonstração do Fluxo de Caixa (DFC).',
        'Risco duplicado na inadimplência: se um cliente fica inadimplente numa venda a prazo em que o Split Payment foi acionado, o distribuidor perde a mercadoria, o lucro e ainda tem o imposto retido de forma compulsória na transação originária, dependendo de complexos processos de ressarcimento.',
        'Exigência de compliance em tempo real: erros de parametrização fiscal ou falhas na vinculação entre a nota fiscal e a liquidação financeira travarão o recebimento do valor líquido da empresa, gerando gargalos operacionais imediatos no faturamento.',
      ]},
      { type: 'callout', text: 'Estudos de grandes auditorias apontam que a perda do float tributário pode exigir que distribuidoras aumentem suas reservas de capital de giro em até 25% para manter o mesmo volume de compras atual.' },
      { type: 'h', text: 'Como a inteligência de dados compensa o imposto retido na fonte' },
      { type: 'p', text: 'Se o governo removeu o colchão financeiro dos tributos, a eficiência necessária para manter a operação saudável precisa vir de dentro. A resposta para o Split Payment não está na busca por mais crédito bancário, mas na inteligência de dados aplicada à eficiência de caixa e estoque. É aqui que o ecossistema da Sewe Group atua como o escudo da sua operação. Através da plataforma de Inteligência de Negócios e IA preditiva, mitigamos o impacto em três frentes cirúrgicas:' },
      { type: 'list', items: [
        'Visibilidade dinâmica de fluxo de caixa: desenhamos cenários de DFC prevendo as entradas já líquidas de IBS/CBS, alertando o CFO sobre descasamentos de prazos antes que virem uma crise de liquidez.',
        'Análise de crédito avançada com BI: automatizamos e refinamos a concessão de crédito para combater a inadimplência, garantindo que o capital não seja alocado em clientes de alto risco sob o novo regime tributário.',
        'Otimização extrema de estoque (IA por SKU): se o imposto drena o caixa, devolvemos o equilíbrio financeiro eliminando o aging (produtos parados). A IA da Sewe calcula os dias úteis ideais de estoque por SKU, destravando capital que antes ficava paralisado em mercadorias obsoletas e devolvendo a liquidez que o Split Payment confiscou.',
      ]},
      { type: 'image', src: '/assets/blog/split-payment-distribuicao/fluxo-de-caixa.jpg', alt: 'Gráfico de análise anual de fluxo de caixa com vendas totais, custos fixos e caixa acumulado', caption: 'Cenários de fluxo de caixa já líquidos de IBS/CBS antecipam o aperto antes que ele aconteça.' },
      { type: 'quote', text: 'Gerenciar uma distribuidora com a regra do Split Payment exige precisão absoluta. Não há mais espaço para gerir o caixa com base no faturamento bruto. A Sewe Group nos deu a visibilidade granular do fluxo de caixa e o controle de estoque necessários para digerir a perda do float tributário sem comprometer nossa capacidade de investimento.', who: 'Alessandro · CEO da Multiseg Distribuidora' },
    ],
    references: [
      { source: 'EY Brasil (Ernst & Young)', label: 'Reforma Tributária e o Mecanismo de Split Payment: Impactos Estruturais no Capital de Giro', url: 'https://www.ey.com/pt_br/tax', note: 'Análises técnicas sobre os impactos da transição tributária do IBS/CBS no caixa corporativo.' },
      { source: 'FGV Direito SP (Núcleo de Estudos Fiscais)', label: 'A Assimetria Temporal do IBS/CBS e os Desafios do Fluxo de Caixa Empresarial', url: 'https://direitosp.fgv.br', note: 'Pesquisas jurídicas e econômicas sobre os gargalos do recolhimento na fonte para o setor produtivo.' },
      { source: 'Portal da Legislação Federal (Planalto)', label: 'Lei Complementar nº 214/2025 e Lei Complementar nº 227/2026, regulamentação do sistema de arrecadação unificada', url: 'https://www.planalto.gov.br', note: 'Atos normativos e textos consolidados das leis complementares que regem o novo ecossistema fiscal brasileiro.' },
    ],
  },
  {
    slug: 'vencedor-premio-2025-diamaju',
    category: 'premio',
    year: '2025',
    title: 'Diamaju, Vencedora do Prêmio SEWE 2025',
    date: '2025-12-10',
    readTime: '4 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'Crescimento acelerado com foco, organização e dados na palma da mão: a divisão PET da Diamaju cresceu +30,2% em faturamento após adotar o BI SEWE.',
    cover: { tag: 'PRÊMIO SEWE · 2025', logo: 'assets/logo-diamaju.png', logoBg: '#eef0f2' },
    blocks: [
      { type: 'lead', text: 'Crescimento acelerado com foco, organização e dados na palma da mão.' },
      { type: 'p', text: 'A Diamaju é uma empresa de grande porte, com atuação em múltiplas verticais. A divisão PET passou a ganhar protagonismo a partir de uma mudança estratégica de gestão e da adoção do BI SEWE no início de 2025.' },
      { type: 'p', text: 'Com os dados centralizados e acessíveis para toda a equipe comercial, representantes, promotores, televendas e supervisores, a empresa passou a operar com mais clareza, alinhamento e foco em oportunidades reais.' },
      { type: 'h', text: 'Principais avanços com o BI' },
      { type: 'metrics', items: [
        { value: '+30,2%', label: 'de crescimento em faturamento na divisão PET' },
        { value: '+22,7%', label: 'na positivação de clientes (+100 novos clientes ativos)' },
        { value: '+26,6%', label: 'no mix de produtos vendidos' },
        { value: '+15%', label: 'no ticket médio por cliente' },
        { value: '114', label: 'usuários ativos no BI, incluindo campo e gestão' },
      ]},
      { type: 'p', text: 'O reconhecimento da Diamaju mostra o que acontece quando a cultura de decisão por dados chega a toda a operação comercial, do representante à diretoria.' },
    ],
  },
  {
    slug: 'vencedor-premio-2025-eletransol',
    category: 'premio',
    year: '2025',
    title: 'Eletransol, Vencedora do Prêmio SEWE 2025',
    date: '2025-12-10',
    readTime: '4 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'Mais organização, menos dependência e decisões mais seguras: a Eletransol reduziu churn em 23,9% e a dependência dos Top 10 clientes com o BI SEWE.',
    cover: { tag: 'PRÊMIO SEWE · 2025', logo: 'assets/logo-eletransol.png', logoBg: '#eef0f2' },
    blocks: [
      { type: 'lead', text: 'Mais organização, menos dependência e decisões mais seguras.' },
      { type: 'p', text: 'A Eletransol se destacou pelo avanço consistente na organização dos processos e no uso estratégico dos dados para gestão comercial, financeira e de suprimentos.' },
      { type: 'p', text: 'Antes do BI, grande parte das análises era feita por planilhas manuais, o que tornava a gestão mais lenta e sujeita a erros operacionais. Com a implementação do BI SEWE, a empresa passou a ter uma visão clara do negócio e maior controle sobre indicadores críticos.' },
      { type: 'h', text: 'Principais avanços com o BI' },
      { type: 'metrics', items: [
        { value: '15,2% → 10%', label: 'redução da dependência dos Top 10 clientes' },
        { value: '+6%', label: 'de crescimento no ticket médio' },
        { value: '−23,9%', label: 'no churn de clientes' },
        { value: '+50,4%', label: 'no valor de orçamentos recebidos (2025 vs. 2024)' },
        { value: '67h', label: 'de desenvolvimento dedicado, com alto nível de personalização' },
      ]},
      { type: 'list', items: [
        'Expansão da base ativa, com mais clientes atendidos por mês.',
        'Gestão comercial, financeira e de suprimentos guiada por indicadores.',
      ]},
      { type: 'p', text: 'A trajetória da Eletransol prova que sair da planilha manual para o dado vivo não é só ganho de tempo, é decisão mais segura e menos risco concentrado.' },
    ],
  },
  {
    slug: 'vencedor-premio-2024-petsul',
    category: 'premio',
    year: '2024',
    title: 'PetSul, Vencedora do 1º Prêmio SEWE',
    date: '2025-02-11',
    readTime: '3 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'A primeira distribuidora reconhecida pelo Prêmio SEWE: a PetSul fortaleceu a venda de campo, organizou indicadores e acelerou o crescimento com análises estratégicas.',
    cover: { tag: 'PRÊMIO SEWE · 2024', logo: 'assets/logo-petsul.png', logoBg: '#ffffff' },
    blocks: [
      { type: 'lead', text: 'A primeira empresa a receber o Prêmio SEWE de Gestão Inteligente e Prosperidade.' },
      { type: 'p', text: 'A PetSul foi uma das duas empresas reconhecidas na primeira edição do prêmio por sua gestão inteligente de dados, trabalhando lado a lado com a equipe SEWE para transformar informação em resultado.' },
      { type: 'h', text: 'O que destacou a PetSul' },
      { type: 'list', items: [
        'Fortalecimento da estratégia de vendas de campo.',
        'Mais controle e indicadores organizados para a gestão.',
        'Crescimento acelerado por meio de análises estratégicas.',
        'Um modelo de distribuição focado nos detalhes, com visão clara de eficiência.',
      ]},
      { type: 'quote', text: 'A SEWE foi a grande ferramenta que concretizou nossas ideias, transformando nossa visão estratégica em realidade e ampliando nossa capacidade de análise e identificação de oportunidades.', who: 'Karin Cecilia · CEO da PetSul' },
      { type: 'p', text: 'Hoje a PetSul é referência em distribuição no mercado Pet no Brasil, e segue em frente, sempre em busca do aprimoramento contínuo.' },
    ],
  },
  {
    slug: 'vencedor-premio-2024-multiseg',
    category: 'premio',
    year: '2024',
    title: 'Multiseg, Vencedora do Prêmio SEWE',
    date: '2025-02-24',
    readTime: '3 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'A segunda entrega do Prêmio SEWE: a Multiseg se destacou pela evolução operacional, redução de estoque em 20% e autonomia das filiais apoiada em dados.',
    cover: { tag: 'PRÊMIO SEWE · 2024', logo: 'assets/logo-multiseg-black.png', logoBg: '#eef0f2' },
    blocks: [
      { type: 'lead', text: 'Evolução operacional e autonomia das filiais, com decisão apoiada em dados.' },
      { type: 'p', text: 'A Multiseg se destacou pelo uso estratégico da análise de dados, impulsionando seu crescimento e aprimorando sua gestão ao lado da equipe SEWE. Foi a segunda empresa a receber o Prêmio SEWE de Gestão Inteligente e Prosperidade.' },
      { type: 'h', text: 'Principais avanços com o BI' },
      { type: 'metrics', items: [
        { value: '−20%', label: 'de estoque, com mais eficiência operacional' },
        { value: '+autonomia', label: 'das filiais para decidir com base em dados' },
        { value: '+crescimento', label: 'sustentado pela análise estratégica' },
      ]},
      { type: 'p', text: 'Decisões bem fundamentadas fazem a diferença no sucesso de um negócio. O reconhecimento da Multiseg celebra mais um ano de conquistas guiadas por dados.' },
    ],
  },
  {
    slug: 'curva-abc-capital-de-giro',
    category: 'blog',
    title: 'Curva ABC e IA preditiva: destrave capital de giro no estoque',
    date: '2026-05-28',
    readTime: '8 min de leitura',
    author: 'Alex de Souza',
    excerpt: 'Política de estoque linear trava o caixa. Veja como a Curva ABC com IA preditiva, calculada por SKU, destrava capital de giro imobilizado na distribuição.',
    cover: { tag: 'GESTÃO ESTRATÉGICA · SUPPLY CHAIN & FINANÇAS', metric: 'A·B·C', metricLabel: 'participação no faturamento' },
    cta: { primary: 'Agendar Diagnóstico de Capital de Giro e Supply', secondary: 'Falar com um Especialista Operacional' },
    blocks: [
      { type: 'lead', text: 'Em médias e grandes operações de distribuição, o colapso do fluxo de caixa raramente acontece por um evento súbito. Ele ocorre de forma silenciosa, gota a gota, através do capital imobilizado em prateleiras repletas de produtos com baixa velocidade de escoamento. Quando a liderança falha em enxergar o estoque como dinheiro sob risco, a eficiência operacional da companhia é severamente comprometida.' },
      { type: 'p', text: 'A tradicional Curva ABC surge como o primeiro framework para estancar essa sangria, classificando os SKUs de acordo com sua representatividade no faturamento. Teoricamente, uma minoria de itens (Curva A) sustenta o negócio, enquanto a cauda longa (Curva C) deveria demandar o mínimo de exposição financeira. Contudo, na dinâmica de mercado atual, gerenciar essa matriz através de planilhas estáticas ou relatórios retroativos do ERP é o equivalente a dirigir olhando apenas pelo retrovisor: você descobre que o caixa travou quando o capital de giro já virou poeira no galpão.' },
      { type: 'image', src: '/assets/blog/curva-abc-capital-de-giro/curva-abc.jpg', alt: 'Centro de distribuição com empilhadeira e um painel de análise de estoque pela Curva ABC, com as classes A, B e C', caption: 'Curva ABC no chão do CD: poucos itens (classe A) concentram a maior parte do valor do estoque.' },
      { type: 'h', text: 'O erro mais comum (e financeiramente letal) da gestão generalista' },
      { type: 'p', text: 'O erro mais crítico cometido por Diretores de Compras e CFOs é a aplicação de uma política linear de cobertura, como a clássica decisão de fixar "45 dias de estoque" para toda a operação. Essa padronização ignora a volatilidade de demanda de cada SKU e gera um duplo desastre financeiro: superestocagem crônica da Curva C (gerando custos altíssimos de holding cost, obsolescência e aging) e, simultaneamente, a ruptura catastrófica da Curva A. Faltar o produto campeão de vendas destrói a margem líquida e entrega o cliente diretamente para a concorrência.' },
      { type: 'list', items: [
        'Cálculo de dias úteis dinâmicos por SKU: abandonar médias globais é mandatório. Cada item da Curva A precisa ter seus dias ideais calculados com base na velocidade real de escoamento e no lead time do fornecedor, eliminando o custo oculto das vendas perdidas.',
        'Governança agressiva sobre o aging da Curva C: itens de baixo giro devem ser submetidos a previsões de demanda restritivas. O foco é a liberação de liquidez: reduzir coberturas ao limite de segurança, renegociar prazos de pagamento com a indústria e liquidar estoques obsoletos para estancar a perda de custo de oportunidade.',
        'Cruzamento de giro vs. margem contábil: a verdadeira inteligência de negócios não avalia o SKU apenas pelo volume faturado. É preciso cruzar a Curva ABC com a margem de contribuição real e o centro de custos logístico. Muitas vezes, um item da Curva A drena a rentabilidade devido ao seu custo de armazenagem, enquanto um Curva B ou C sustenta o lucro líquido.',
      ]},
      { type: 'callout', text: 'Grande parte do capital de giro de um distribuidor pode ficar paralisada em SKUs sobrealocados quando a Curva ABC não é recalculada diariamente.' },
      { type: 'p', text: 'Para transformar o estoque em um motor de lucratividade, a Sewe Group desenvolveu uma suíte de Suprimentos & Logística Inteligente alimentada por IA preditiva. A tecnologia ingere longos históricos de vendas e dados macroeconômicos para estimar com precisão o volume de compras dos próximos meses por SKU. Ao integrar-se nativamente ao seu ERP, a plataforma calcula os dias úteis ideais para cada produto de forma individualizada, automatizando a decisão do comprador e garantindo que cada centavo do capital de giro seja alocado onde há garantia de retorno.' },
      { type: 'quote', text: 'Antes da Sewe Group, nossa gestão de compras operava sob a premissa de coberturas fixas, o que sobrecarregava nosso fluxo de caixa com produtos parados e nos expunha a rupturas severas nos itens de alto giro. A Inteligência Artificial da Sewe redesenhou nossa política de suprimentos por SKU. O resultado foi imediato: reduzimos drasticamente o aging do estoque, eliminamos o custo de vendas perdidas e destravamos milhões em capital de giro que hoje financiam nossa expansão.', who: 'Alessandro · CEO da Multiseg Distribuidora' },
    ],
    references: [
      { source: 'Gartner', label: 'Predictive Analytics in Supply Chain: Moving Beyond Static Inventory Models', url: 'https://www.gartner.com/en/supply-chain', note: 'Insights globais sobre a substituição de modelos estáticos por algoritmos preditivos na cadeia de suprimentos.' },
      { source: 'McKinsey & Company', label: 'Unlocking Working Capital: The Power of Granular Inventory Optimization', url: 'https://www.mckinsey.com/capabilities/operations/our-insights', note: 'Estudos de caso e metodologias sobre como a otimização de inventário libera liquidez imediata.' },
      { source: 'ASCM (Association for Supply Chain Management)', label: 'Supply Chain Body of Knowledge (SCBOK), Advanced Inventory Classification Techniques', url: 'https://www.ascm.org', note: 'Frameworks globais de governança e classificação avançada de ativos circulantes.' },
    ],
  },
];
